export declare enum AUTHORIZED_DEVICE_STATUS {
    AUTHORIZED_DEVICE_STATUS_YES = "YES",
    AUTHORIZED_DEVICE_STATUS_WAITING = "WAITING",
    AUTHORIZED_DEVICE_STATUS_NO = "NO"
}
export declare enum REQUESTDEVICESTATUS {
    CONNECT_STATUS_YES = "YES",
    CONNECT_STATUS_WAITING = "WAITING",
    CONNECT_STATUS_NO = "NO"
}
export declare enum DEVICE_EVENT {
    DEVICE_CONNECT = "DEVICE_CONNECT",
    DEVICE_DISCONNECT = "DEVICE_DISCONNECT",
    DEVICE_UPDATE_REQUEST_DEVICE_STATUS = "DEVICE_UPDATE_REQUEST_DEVICE_STATUS"
}
